Update alist.yml

diff --git a/.github/workflows/alist.yml b/.github/workflows/alist.yml
--- a/.github/workflows/alist.yml
+++ b/.github/workflows/alist.yml
@@ -1,4 +1,4 @@
-name: Build Alist 
+name: Build Alist
 
 on:
   repository_dispatch:
@@ -8,36 +8,38 @@ on:
         description: 'Tag to release'
         required: true
         default: '0.0.1'
-        
+
 jobs:
-
   build:
-
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - uses: actions/checkout@v2
-    - name: docker login
+    - uses: actions/checkout@v4
+
+    - name: Docker login
       env:
-        DOCKER_USER: ${{secrets.DOCKER_USER}}
-        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
+        DOCKER_USER: ${{ secrets.DOCKER_USER }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       run: |
-        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
-        
+        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
+
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v3
+
     - name: Set up Docker Buildx
-      id: buildx
-      uses: crazy-max/ghaction-docker-buildx@v3
-      with:
-          buildx-version: latest
-          qemu-version: latest
-    - name: Available platforms
-      run: echo ${{ steps.buildx.outputs.platforms }}
+      uses: docker/setup-buildx-action@v3
+
+    - name: Check Alist directory
+      run: |
+        if [ ! -d "Alist" ]; then echo "Alist directory not found"; exit 1; fi
+
     - name: Run Buildx
       run: |
-          cd Alist
-          docker buildx build . \
-            --platform linux/amd64 \
-            --output "type=image,push=true" \
-            --file Dockerfile-hub \
-            --tag skylerhe/alist:latest
+        cd Alist
+        docker buildx build . \
+          --platform linux/amd64,linux/arm64,linux/armv7 \
+          --output "type=image,push=true" \
+          --file Dockerfile-hub \
+          --tag skylerhe/alist:${{ github.event.inputs.tag }} \
+          --tag skylerhe/alist:latest
